package com.stressthem.app.initialization;

import com.stressthem.app.domain.entities.Ticket;
import com.stressthem.app.repositories.TicketRepository;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.boot.CommandLineRunner;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Component;

import java.time.LocalDateTime;
import java.time.ZoneId;


@Component
@Order(value = 7)
public class TicketInitialization implements CommandLineRunner {
    private TicketRepository ticketRepository;

    @Autowired
    public TicketInitialization(TicketRepository ticketRepository) {
        this.ticketRepository = ticketRepository;
    }

    @Override
    public void run(String... args) throws Exception {
       Ticket ticket=new Ticket("test@request.wtf","This is a test ticket","This is a autogenerated ticket with test purposes",true, LocalDateTime.now(ZoneId.systemDefault()));
    this.ticketRepository.save(ticket);
    }
}
